# ================================================================================
# Framework Routing common configuration
# ================================================================================
framework:
    router:
        strict_requirements: ~
        utf8: true
