# ================================================================================
# Security configuration
# ================================================================================
security:

    # ---------------------------
    # Password encoders
    # ---------------------------
    encoders:
        App\Entity\User:
            algorithm: auto
            cost: 15

    # ---------------------------
    # Providers
    # ---------------------------



    # ---------------------------
    # Firewalls
    # ---------------------------
    firewalls:

        # Developer's area (profiler, debug toolbar, etc.)
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


        # Authentication section (login, logout, and so on)
        auth:
            pattern: ^/api/auth/login
            stateless: true
            anonymous: true

            json_login:
                check_path: /api/auth/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

            logout:
                path: /api/security/logout


        # API section. Protected by firewall
#        api:
#            pattern: ^/api
#            stateless: true
#
#            guard:
#                provider: main
#                authenticators:
#                    - lexik_jwt_authentication.jwt_token_authenticator



    # ---------------------------
    # Access control rules
    # ---------------------------
    access_control:
#        - { path: ^/api/auth,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }