# ================================================================================
# Swiftmailer configuration
# ================================================================================
swiftmailer:
    transport: '%env(MAILER_TRANSPORT)%'
    host: '%env(string:MAILER_HOST)%'
    username: '%env(string:MAILER_USERNAME)%'
    password: '%env(string:MAILER_PASSWORD)%'
    auth_mode: login
    encryption: ssl