# ================================================================================
# Framework Validator common configuration
# ================================================================================

framework:
    validation:
        email_validation_mode: html5
