# ================================================================================
# Framework Routing configuration for dev env
# ================================================================================
framework:
    router:
        strict_requirements: true
