# ================================================================================
# Swiftmailer configuration for test env
# ================================================================================
swiftmailer:
    # send all emails to a specific address
    delivery_address: '%env(string:MAILER_DELIVERY_ADDRESS)%'
