# ================================================================================
# Framework Web profiler configuration for dev env
# ================================================================================

web_profiler:
    toolbar: true
    intercept_redirects: false

framework:
    profiler: { only_exceptions: false }
